### ISSUE TITLE
There is a problem with the kick command code

### ISSUE THREAD

**Issue by Nathithegamer99** [Mr-warriyo/Mr-warriyo-discord.js#2]
my bot keeps saying I cannot kick this user why? pls help me fix it
![Screenshot_20210321-075841_Discord](https://user-images.githubusercontent.com/80963869/111895455-4d443d80-8a1b-11eb-9f02-ce9e7b4fa80b.jpg)

**Comment by 19akshansh** [comment]
Hey,
Sorry for that problem.. I have edited the code now and it's working also..
You can obtain the new code from "Ep - 5" folder "kick.js"  file..
Thank you!

**Comment by Nathithegamer99** [comment]
Thx love your videos man!
